version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      
    environment:
      
  web:
    build: .
    command: >
      sh -c "uvicorn main:app --reload"
    volumes:
     
    ports:
    environment:
    depends_on:
    